#redis集群
server:
  port: 9999

spring:
  application:
    name: springboot-redis-cluster
  redis:
    password:
    cluster:
      nodes: 192.168.2.20:6379,192.168.2.20:6380,192.168.2.20:6381,192.168.2.20:6382,192.168.2.20:6383,192.168.2.20:6384
      max-redirects: 3
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000
    